FROM debian/jessie

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get clean && \
    apt-get update -qy && apt-get install -qy --no-install-recommends \
     apt-transport-https

COPY deployment.tar.gz /opt/deployment.tar.gz
RUN cd /opt && tar xvfz deployment.tar.gz

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN mkdir -p /opt/test-config/group_vars
COPY test-config/inventory /opt/test-config
COPY test-config/%service_name% /opt/test-config/group_vars
COPY ansible.cfg  /opt/ansible.cfg

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

